version: '3'
services:
  frontend:
    image: your-dockerhub-username/frontend:latest
    ports:
      - "80:80"
  backend:
    image: your-dockerhub-username/backend:latest
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=mysql://db_user:db_pass@db_host:3306/db_name
  database:
    image: your-dockerhub-username/database:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass
      - MYSQL_DATABASE=db_name
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_pass
