version: '3.7'

services:
  frontend:
    image: roman2447/frontend:latest
    ports:
      - "3000:3000"

  backend:
    image: roman2447/backend:latest
    ports:
      - "5000:5000"

volumes:
  jenkins_home:
