pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/RomanNft/site_diplom1.git'
            }
        }
        stage('Build') {
            steps {
                script {
                    dir('backend') {
                        sh 'docker build -t roman2447/backend:latest .'
                    }
                }
            }
        }
        stage('Push') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-credentials-id', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    script {
                        sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                        sh 'docker push roman2447/backend:latest'
                    }
                }
            }
        }
    }
}
