pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git url: 'https://github.com/RomanNft/site_diplom1.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    def imageName = "roman2447/database:latest"
                    sh "docker build -t ${imageName} ."
                    withDockerRegistry([credentialsId: 'dockerhub-creds', url: '']) {
                        sh "docker push ${imageName}"
                    }
                }
            }
        }
    }
}
